### ISSUE TITLE
muokkaa henkilö

### ISSUE THREAD

**Issue by JoriJalkanen** [Shipsoftware-schoolproject/shipsoftware-php#1]
Muokaa henkilö nappi ei päivitä

@tomi voitko tarkentaa?

**Comment by Lihis** [comment]
Kun henkilöä on muokattu, tiedot ei päivity \<table\>:een, henkilöt listan alla.

Mahdollisesti myös vikaa poistossa, sivun päivittämisen jälkeen tyhjä rivi näkyy listassa -> tästä erillinen issue mikäli poistossa on vikaa

**Comment by Lihis** [comment]
After starting to use PHP framework this is not an issue anymore, closing.
