### ISSUE TITLE
Ship information page doesn't show google maps

### ISSUE THREAD

**Issue by JoriJalkanen** [Shipsoftware-schoolproject/shipsoftware-php#2]
ship information page doesn't show google maps

**Comment by Lihis** [comment]
Google Maps is now behind paywall and thus requires credit card to be associated with the API. So, it seems that the "free" 200$/month also requires a credit card as our maps are now watermarked.

Might be better to look for another map provider which is easiest to migrate into. [Mapbox](https://www.mapbox.com/) might be viable option?

**Comment by Lihis** [comment]
Mapbox doesn't differ much from Google expect; X number of free calls to the API but if you exceed the monthly quota and you don't have valid payment method your account will get disabled until you add payment method.

**Comment by Lihis** [comment]
Closed via #3
